# Set language and version
language: ruby
rvm:
  - 2.2

# Travis optimizations
cache: bundler
sudo: false

# Install required services
services:
  - redis-server

# Set environment variables
env:
  - REDIS_URL="redis://localhost:6379"
